on:
  workflow_call:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - run: echo step 1
      - run: echo step 2
      - continue-on-error: ${{ vars.CONTINUE_ON_ERROR == 'true' }}
        run: echo step 3 failed && exit 1
      - run: echo step 4
      - run: echo step 5
